import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import type { ReactNode } from 'react';

import '../shared/styles/globals.scss';
import { Sidebar } from '@/widgets/sidebar';

const inter = Inter({
  style: ['normal'],
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Framegram',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <div className='container'>
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
