import type { Metadata } from 'next';

import type { ReactNode } from 'react';

import '../shared/styles/globals.scss';
import { Header } from '@/widgets/header/ui/Header';
import { AppProviders } from '@/app/provider/AppProviders';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import { AppTanstackProviders } from '@/app/provider/me-provider';
import { GoogleAnalytics } from '@next/third-parties/google';

export const metadata: Metadata = {
  title: 'Framegram',
  description: 'Generated by create next app',
};

import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      className={inter.variable}
    >
      <body>
        <AppProviders>
          <AppTanstackProviders>
            <NextIntlClientProvider>
              <div className='wrapper'>
                <Header />
                <div className='mainBox'>
                  <main className='main'>{children}</main>
                </div>
              </div>
            </NextIntlClientProvider>
          </AppTanstackProviders>
        </AppProviders>
      </body>
      <GoogleAnalytics gaId='G-YCCX45VF8W' />
    </html>
  );
}
