export const routes = {
  auth: {
    registration: '/registration',
    login: '/login',
    confirmEmail: '/confirm-email',
    logout: '/logout',
    forgot: '/forgot-password',
    newPassword: '/new-password',
  },
  legal: {
    policy: '/legal/policy',
    terms: '/legal/terms',
  },
  empty: '',
  feed: '/feed',
  main: '/',
  create: '/create',
  profile: '/profile',
  publicProfile: '/profile',
  messenger: '/messenger',
  search: '/search',
  statistics: '/statistics',
  favorites: '/favorites',
  notAuth: '/not-auth',
} as const;
